### ISSUE TITLE
Bad security of `/dev/uinput`

### ISSUE THREAD

**Issue by maxbla** [Kerndog73/The-Fat-Controller#1]
this line of the readme
`sudo sh -c 'echo -e "KERNEL==\"uinput\", MODE=\"0666\"" >> /etc/udev/rules.d/50-uinput.rules'`
Lets any userspace program simulate user input persistent across reboots, which is not enabled by default for Linux for a reason - it is a security issue. This should be clarified in the readme (in addition to how to remove this for Linux newbies).

The proper way to deal with this for production software is to create a separate group (see [weylus'](https://github.com/H-M-H/Weylus#linux) readme)

The proper way to deal with it for one off local development is probably `chmod`, as it is not persistent across reboots

**Comment by indianakernick** [comment]
Thanks for pointing this out. The README has been updated. Let me know what you think and I'll publish a new release to update it on crates.io.

**Comment by maxbla** [comment]
Looks good to me! after changing the .rules file, you don't have to reboot, you can also [udevadm control --reload-rules](https://unix.stackexchange.com/questions/39370/how-to-reload-udev-rules-without-reboot)

**Comment by indianakernick** [comment]
I published a new version for this to update the crates.io README.
