### ISSUE TITLE
Unable to compile in Windows 11

### ISSUE THREAD

**Issue by Roconx** [Kerndog73/The-Fat-Controller#8]
This crate works perfectly on macos but in Windows 11 it will simply not compile:
![image](https://user-images.githubusercontent.com/69419903/201514896-19ea1999-c487-4066-9a7a-7b88b8ceb747.png)

Let me know if you need any extra info!
Thanks in advance!

**Comment by indianakernick** [comment]
This is probably due to an out-of-date version of Rust. See [the docs](https://doc.rust-lang.org/stable/std/ffi/type.c_int.html). That feature has been supported since 1.64.

**Comment by Roconx** [comment]
Works flawlessly after updating! Thanks for you fast response!
Had version 1.61 ....
